:doctitle: {artifact}: {major}{minor}{patch}{extension}{build}
:imagesdir: images
:data-uri:
:group: io.docops
:artifact: docops-button-render
:major: 2022
:minor: .7
:patch:
:build:
//:extension:
:extension: -SNAPSHOT

== Maven

[subs="+attributes"]
----
<dependency>
  <groupId>{group}</groupId>
  <artifactId>{artifact}</artifactId>
  <version>{major}{minor}{patch}{extension}{build}</version>
</dependency>
----

== Gradle
[subs="+attributes"]
----
implementation("{group}:{artifact}:{major}{minor}{patch}{extension}{build}")
----
[subs="+attributes"]
----
implementation '{group}:{artifact}:{major}{minor}{patch}{extension}{build}'
----

== Source

link:https://github.com/docops-info/{artifact}[]

== Download

link:https://search.maven.org/remotecontent?filepath=io/docops/{artifact}/{major}{minor}{patch}{extension}{build}/{artifact}-{major}{minor}{patch}{extension}{build}.jar[{artifact}-{major}{minor}{patch}{extension}{build}.jar] [small]#link:https://repo1.maven.org/maven2/io/docops/{artifact}/{major}{minor}{patch}{extension}{build}/{artifact}-{major}{minor}{patch}{extension}{build}.jar.asc[[gpg sig\]]#


== Document

link:build/docs/{artifact}.html[]

== History

2022.6 - 2022-06-07::
* css updates

2022.5 - 2022-04-19::
* Security and currency

2022.4 - 2022-04-04::
* View box updates

2022.3 - 2022-03-21::
* Fixed Round Button

2022.2 - 2022-03-11::
* Fixed Round Button width

2022.1 - 2022-03-02::
* Improved round buttons

2022.0 - 2022-02-13::
* Initial release to Maven Central.

== DocOps

image::docops.svg[DocOps,150,150,float="right",link="https://docops.io/"]

Document Operations (DocOps) is a documentation philosophy based on agile software product development. Simply put, DocOps promotes the ideas, that everyone that develops a product should document it from their perspective in small fragments using the tools they use.  Dynamic documents are assembled from the fragments to meet the needs of a given audience.

We are a group of product developers that have been challenged multiple times to unravel the task of large scale, multi-audience documentation.  We are developing a series of tools and services to lower the barriers of DocOps at any scale.  Often leveraging other open source projects from other amazing teams and fantastic engineers, we are developing the best documentation experience we can.

link:https://docops.io/[docops.io]
